###### You can use these custom detector locations with PyCBC tools 
# either by explicitly invoking `pycbc.detector.load_detector_config`
# or setting the PYCBC_DETECTOR_CONFIG path variable to this file

[detector-CE_A]
method = earth_normal
# Radians
latitude = 0.8028514559173915
longitude = -2.1816615649929116
yangle = 1.7453292519943295
xlength = 40000
ylength = 40000

[detector-CE_B]
method = earth_normal
# Radians
latitude = 0.5061454830783556 
longitude = -1.6406094968746698
yangle = 2.792526803190927
xlength = 20000
ylength = 20000

# ET detector in Serdinia, Italy, PSD from PSD data from https://apps.et-gw.eu/tds/?content=3&r=18213 3rd column and Tab II https://arxiv.org/pdf/2307.10421; 
# https://github.com/cosmic-explorer/mpsac_detector_networks/blob/main/doc/Network_configurations_for_MPSAC.pdf

[detector-ETS]
method = earth_normal
length = 10
latitude = 40.0 + 31. / 60 + 0.0 / 3600
longitude = 9.0 + 25. / 60 + 0.0 / 3600
elevation = 300.0
xarm_azimuth = 349.40
yarm_azimuth = 49.40
shape = 'Triangle'

# MPSAC https://github.com/cosmic-explorer/mpsac_detector_networks and https://cosmicexplorer.org/celocations.html Tab II of https://arxiv.org/pdf/2307.10421
# Texas

[detector-CEA]
method = earth_normal
length = 40
latitude = 46
longitude = -125
elevation = 142.554
xarm_azimuth = 260.0
yarm_azimuth = 350.0
xarm_tilt = -6.195e-4
yarm_tilt = 1.25e-5

[detector-CEB]
# Washington
method = earth_normal
length = 20
latitude = 29
longitude = -94
elevation = 142.554
xarm_azimuth = 200.0
yarm_azimuth = 290.0
xarm_tilt = -6.195e-4
yarm_tilt = 1.25e-5

